version: "3.8"

# Application Name = COMPOSE_PROJECT_NAME
name: Example

networks:
  laravel:
    driver: bridge

services:
  # Laravel Application Service
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
    depends_on:
      - db
    networks:
      - laravel

  # PostgreSQL Database Service
  db:
    image: postgres
    container_name: ${COMPOSE_PROJECT_NAME}_db
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${COMPOSE_PROJECT_NAME}
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    networks:
      - laravel

  # Nginx Web Server Service
  nginx:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
    networks:
      - laravel

  # pgAdmin Service
  pgadmin:
    image: dpage/pgadmin4
    container_name: ${COMPOSE_PROJECT_NAME}_pgadmin_ui
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
    networks:
      - laravel
