version: "3.8"

networks:
  laravel:
    driver: bridge

services:
  app:
    container_name: laravel_app
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel

  db:
    image: postgres
    container_name: postgres_db
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d blog"]
      interval: 5s
      retries: 5
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
    networks:
      - laravel

  # pgAdmin Service
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel
